// Shared brand constants and layout utilities for all Tyoutor Pro PDF exports

export type RGB = [number, number, number]

export const G = {
  green:   [45, 106, 79]   as RGB,
  accent:  [82, 183, 136]  as RGB,
  terra:   [224, 122, 95]  as RGB,
  dark:    [26, 26, 26]    as RGB,
  body:    [85, 85, 85]    as RGB,
  sub:     [136, 136, 136] as RGB,
  muted:   [170, 170, 170] as RGB,
  lightBg: [248, 247, 242] as RGB,
  border:  [232, 228, 222] as RGB,
  terraBg: [255, 244, 240] as RGB,
  white:   [255, 255, 255] as RGB,
}

export const PAGE = {
  W:        210 as const,  // A4 width mm
  H:        297 as const,  // A4 height mm
  M:        14  as const,  // left/right margin
  CW:       182 as const,  // content width (W - 2*M)
  FOOTER_Y: 279 as const,  // y of footer separator line
}

// Draws the branded header on the current page.
// Returns the y position where body content should begin.
export function drawPageHeader(
  doc: any,
  title: string,
  subtitle: string,
  teacherName: string,
): number {
  const { M, W, CW } = PAGE

  // ── Logo square ────────────────────────────────────────────────────────────
  doc.setFillColor(G.green[0], G.green[1], G.green[2])
  doc.rect(M, 5, 9, 9, 'F')
  doc.setFontSize(8)
  doc.setTextColor(G.white[0], G.white[1], G.white[2])
  doc.setFont('helvetica', 'bold')
  doc.text('T', M + 4.5, 12.5, { align: 'center' })

  // ── Brand name ─────────────────────────────────────────────────────────────
  doc.setFontSize(11)
  doc.setTextColor(G.green[0], G.green[1], G.green[2])
  doc.setFont('helvetica', 'bold')
  doc.text('Tyoutor Pro', M + 12, 12.5)

  // ── Prepared by (right-aligned) ────────────────────────────────────────────
  doc.setFontSize(9)
  doc.setTextColor(G.sub[0], G.sub[1], G.sub[2])
  doc.setFont('helvetica', 'normal')
  doc.text(`Prepared by ${teacherName}`, W - M, 12.5, { align: 'right' })

  // ── Separator line ─────────────────────────────────────────────────────────
  doc.setDrawColor(G.border[0], G.border[1], G.border[2])
  doc.setLineWidth(0.3)
  doc.line(M, 17, W - M, 17)

  // ── Document title ─────────────────────────────────────────────────────────
  doc.setFontSize(16)
  doc.setTextColor(G.dark[0], G.dark[1], G.dark[2])
  doc.setFont('helvetica', 'bold')
  const titleLines: string[] = doc.splitTextToSize(title, CW)
  doc.text(titleLines, M, 25)
  const afterTitle = 25 + titleLines.length * 6.5

  // ── Subtitle ───────────────────────────────────────────────────────────────
  doc.setFontSize(10)
  doc.setTextColor(G.sub[0], G.sub[1], G.sub[2])
  doc.setFont('helvetica', 'normal')
  doc.text(subtitle, M, afterTitle + 1)

  return afterTitle + 10  // first content starts here
}

// Draws footer (line + text) on every page of the document.
export function drawPageFooters(doc: any, info = ''): void {
  const { M, W, FOOTER_Y } = PAGE
  const n = doc.getNumberOfPages()
  for (let p = 1; p <= n; p++) {
    doc.setPage(p)
    doc.setDrawColor(G.border[0], G.border[1], G.border[2])
    doc.setLineWidth(0.3)
    doc.line(M, FOOTER_Y, W - M, FOOTER_Y)
    doc.setFontSize(8)
    doc.setTextColor(G.muted[0], G.muted[1], G.muted[2])
    doc.setFont('helvetica', 'normal')
    const left = info
      ? `Generated by Tyoutor Pro · tyoutorpro.io  ·  ${info}`
      : 'Generated by Tyoutor Pro · tyoutorpro.io'
    doc.text(left, M, FOOTER_Y + 6)
    doc.text(`Page ${p} of ${n}`, W - M, FOOTER_Y + 6, { align: 'right' })
  }
}
